-- MySQL Script generated by MySQL Workbench
-- Tuesday, 25 April, 2017 11:06:47 PM PHT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OMAS` DEFAULT CHARACTER SET utf8 ;
USE `OMAS` ;

-- -----------------------------------------------------
-- Table `Accountant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Accountant` ;

CREATE TABLE IF NOT EXISTS `Accountant` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UserID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`UserID`));


-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier` ;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(45) NULL,
  `Address` VARCHAR(255) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `PostalCode` INT UNSIGNED NOT NULL,
  `Phone` INT UNSIGNED NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administrator` ;

CREATE TABLE IF NOT EXISTS `Administrator` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `AdminID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(255) NOT NULL,
  `Phone` INT UNSIGNED NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Purchasing Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Purchasing Order` ;

CREATE TABLE IF NOT EXISTS `Purchasing Order` (
  `PurchaseID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SupplierID` INT UNSIGNED NOT NULL,
  `TransactionDate` DATETIME NULL DEFAULT Current_timestamp,
  `Total` FLOAT UNSIGNED NOT NULL,
  `Accountant_UserID` INT NOT NULL,
  `Supplier_SupplierID` INT NOT NULL,
  `Administrator_AdminID` INT NULL,
  `Status` INT(1) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`PurchaseID`),
  CONSTRAINT `fk_Purchasing Order_Accountant1`
    FOREIGN KEY (`Accountant_UserID`)
    REFERENCES `Accountant` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchasing Order_Supplier1`
    FOREIGN KEY (`Supplier_SupplierID`)
    REFERENCES `Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchasing Order_Administrator1`
    FOREIGN KEY (`Administrator_AdminID`)
    REFERENCES `Administrator` (`AdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Purchasing Order_Accountant1_idx` ON `Purchasing Order` (`Accountant_UserID` ASC);

CREATE INDEX `fk_Purchasing Order_Supplier1_idx` ON `Purchasing Order` (`Supplier_SupplierID` ASC);

CREATE INDEX `fk_Purchasing Order_Administrator1_idx` ON `Purchasing Order` (`Administrator_AdminID` ASC);


-- -----------------------------------------------------
-- Table `Sales Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales Invoice` ;

CREATE TABLE IF NOT EXISTS `Sales Invoice` (
  `PurchaseID` INT NOT NULL AUTO_INCREMENT,
  `SupplierID` INT UNSIGNED NOT NULL,
  `TransactionDate` DATETIME NULL DEFAULT Current_timestamp,
  `Total` FLOAT UNSIGNED NOT NULL,
  `Accountant_UserID` INT NOT NULL,
  `Customer_CustomerID` INT NOT NULL,
  `Administrator_AdminID` INT NULL,
  `Status` INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`PurchaseID`),
  CONSTRAINT `fk_Sales Invoice_Accountant1`
    FOREIGN KEY (`Accountant_UserID`)
    REFERENCES `Accountant` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales Invoice_Customer1`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales Invoice_Administrator1`
    FOREIGN KEY (`Administrator_AdminID`)
    REFERENCES `Administrator` (`AdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sales Invoice_Accountant1_idx` ON `Sales Invoice` (`Accountant_UserID` ASC);

CREATE INDEX `fk_Sales Invoice_Customer1_idx` ON `Sales Invoice` (`Customer_CustomerID` ASC);

CREATE INDEX `fk_Sales Invoice_Administrator1_idx` ON `Sales Invoice` (`Administrator_AdminID` ASC);


-- -----------------------------------------------------
-- Table `Purchasing Order Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Purchasing Order Item` ;

CREATE TABLE IF NOT EXISTS `Purchasing Order Item` (
  `ItemID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(45) NULL,
  `ItemDesc` VARCHAR(255) NOT NULL,
  `Quantity` INT UNSIGNED NULL,
  `PO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `fk_POID`
    FOREIGN KEY (`PO_ID`)
    REFERENCES `Purchasing Order` (`PurchaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_POID_idx` ON `Purchasing Order Item` (`PO_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
